# Generated by Django 6.0.2 on 2026-02-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='releaseDate',
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(),
        ),
    ]
