# Generated by Django 6.0.2 on 2026-02-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_release_date_movie_releasedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='bookingDate',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='is_booked',
            new_name='isBooked',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seat_number',
            new_name='seatNumber',
        ),
    ]
